  # ! /usr/bin/env python
  # -*- coding: utf-8 -*-
  #
  # Support module generated by PAGE version 7.5
  # in conjunction with Tcl version 8.6
  # Nov 28, 2022 09:05:29 AM EST  platform: Windows NT

import sys
import tkinter as tk
import SwipeDown

def main():
    """Main entry point for the application."""
    global _root
    _root = tk.Tk()
    _root.protocol('WM_DELETE_WINDOW', _root.destroy)
      # Creates a toplevel widget.
    global _top1, _w1
    _top1 = _root
    _w1 = SwipeDown.SwipeDown(_top1)
    _root.mainloop()

def sqlInject(*args):
    print('SwipeDown_support.def sqlInject')
    for arg in args:
        print('	another arg:', arg)
    sys.stdout.flush()

def xxx(*args):
    print('SwipeDown_support.xxx')
    for arg in args:
        print('	another arg:', arg)

    sys.stdout.flush()



def scrape():
    import time
    import bs4

    from selenium import webdriver
    from selenium.webdriver.chrome.service import Service
    from webdriver_manager.chrome import ChromeDriverManager
    from selenium.webdriver.common.by import By
    from selenium.webdriver.common.keys import Keys


    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
    soup = bs4.BeautifulSoup()
    dorkfile = open('./GoogleHackMasterList.txt', 'r')
    count = 0
    for dork in dorkfile:
        driver.get("https://www.google.com/")
        search = driver.find_element(by=By.NAME, value='q')
        result = search.send_keys(f'{dork}')
        time.sleep(30)
        search.send_keys(Keys.ENTER)
        matches = soup.find_all(result)
        len_match = len(matches)
        count += 1
        time.sleep(300)
        driver.quit()

        with open('./scraping.txt', 'a+') as f:
            for i in matches:
                f.write(str(count) + '.' + i + '\n')
                f.write("There were " + str(len_match) + " matches found for your keyword:\n")
            f.close()

def httpPollute():
    """
     @TODO
     Learn HTTP Parameter Pollution and write a script.
     """

def cssInject():
    """
    @TODO
    learn CSS Injection and create a script for it.
    """

if __name__ == '__main__':
    SwipeDown.start_up()
